// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH46JD8WzBoHCeolkyT9Be3GMW14OkC5Q',
    appId: '1:930119215565:android:4ab5d649078f7d3250bc84',
    messagingSenderId: '930119215565',
    projectId: 'my-expenses-flutter-project',
    storageBucket: 'my-expenses-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwh7uW2h0Yqg0dszARJ4IPRhALFAkwzTw',
    appId: '1:930119215565:ios:9abebed7f077953350bc84',
    messagingSenderId: '930119215565',
    projectId: 'my-expenses-flutter-project',
    storageBucket: 'my-expenses-flutter-project.appspot.com',
    iosClientId: '930119215565-jcspgqfid2362ov3h0825g81kf3896uh.apps.googleusercontent.com',
    iosBundleId: 'com.budgetapp.myexpenses',
  );
}
